// Generated by Wrangler on Thu Aug 01 2024 19:30:15 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	ELASTIC_HOST: 'http://141.5.105.237:9200';
	ELASTIC_APIKEY: "";
}
