// Generated by Wrangler on Mon Aug 05 2024 18:13:51 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	ELASTIC_HOST: "https://141.5.105.237:9200";
	ELASTIC_APIKEY: "";
	ELASTIC_INDEX: "21.11155";
}
