// Generated by Wrangler on Mon Aug 05 2024 18:46:24 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	ELASTIC_HOST: "https://commerce-demo.es.us-east4.gcp.elastic-cloud.com:9243";
	ELASTIC_APIKEY: "a2Rha1VJTUJMcGU4ajA3Tm9fZ0Y6MjAzX2pLbURTXy1hNm9SUGZGRlhJdw==";
	ELASTIC_INDEX: "imdb_movies";
}
