<!-- eslint-disable vue/no-mutating-props -->
<!--     v-model="props.dataJson" -->
<template>
  <FormKit
    v-model="dataJson"
    type="form"
    :actions="false"
  >
    <FormKit
      type="group"
      name="has_record"
      label="has_record"
    >
      <FormKit
        type="text"
        name="category"
        label="category"
        validation="required"
      />
      <FormKit
        type="text"
        name="id"
        label="id"
        validation="required"
      />
      <!--GROUP-->
      <FormKit
        type="group"
        name="has_primary_title"
        label="has_primary_title"
      >
        <FormKit
          type="text"
          name="has_name"
          label="has_name"
          validation="required"
        />
        <FormKit
          type="text"
          name="type"
          label="type"
          validation="required"
        />
      </FormKit>
      <!--GROUP-->
      <FormKit
        type="group"
        name="described_by"
        label="described_by"
      >
        <FormKit
          type="text"
          name="has_issuer_id"
          label="has_issuer_id"
          validation="required"
        />
        <FormKit
          type="text"
          name="has_issuer_name"
          label="has_issuer_name"
          validation="required"
        />
        <FormKit
          type="datetime-local"
          name="last_modified"
          label="last_modified"
          validation="required"
        />
      </FormKit>
      <!--REPEATER-->
      <FormKit
        type="repeater"
        name="has_event"
      >
        <FormKit
          type="text"
          name="category"
          label="category"
          validation="required"
        />
        <FormKit
          type="text"
          name="has_date"
          label="has_date"
          validation="required"
        />
        <!--REPEATER-->
        <FormKit
          type="repeater"
          name="has_activity"
        >
          <FormKit
            type="text"
            name="category"
            label="category"
            validation="required"
          />
          <!--REPEATER-->
          <FormKit
            type="repeater"
            name="has_agent"
          >
            <FormKit
              type="text"
              name="has_name"
              label="has_name"
              validation="required"
            />
            <FormKit
              type="text"
              name="type"
              label="type"
              validation="required"
            />
            <!--REPEATER-->
            <FormKit
              type="repeater"
              name="same_as"
            >
              <FormKit
                type="text"
                name="category"
                label="category"
                validation="required"
              />
              <FormKit
                type="text"
                name="id"
                label="id"
                validation="required"
              />
            </FormKit>
          </FormKit>
        </FormKit>
        <!--REPEATER-->
        <FormKit
          type="repeater"
          name="located_in"
          label="located_in"
          validation="required"
        >
          <FormKit
            type="text"
            name="has_name"
            label="has_name"
          />
          <!--REPEATER-->
          <FormKit
            type="repeater"
            name="same_as"
            label="same_as"
            validation="required"
          >
            <FormKit
              type="text"
              name="category"
              label="category"
            />
            <FormKit
              type="text"
              name="id"
              label="id"
            />
          </FormKit>
        </FormKit>
      </FormKit>
    </FormKit>
  </FormKit>
</template>
<script setup lang="ts">
const dataJson = defineModel({type: Object, required: true});
</script>